server {
    listen 80;
    listen [::]:80;
    server_name tx.nstarzx.cn;

    location ^~ /.well-known/acme-challenge/ {
        root /www/wwwroot/tx.nstarzx.cn;
        default_type text/plain;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }

    access_log /www/wwwlogs/tx.nstarzx.cn_80.log;
    error_log  /www/wwwlogs/tx.nstarzx.cn_80.error.log;
}
