bind 127.0.0.1 -::1
protected-mode yes
port 6380
tcp-backlog 128
timeout 0
tcp-keepalive 300
daemonize no
supervised no
loglevel notice
logfile ""
databases 4
always-show-logo no
aclfile /www/wwwroot/tx.nstarzx.cn/secrets/redis.acl
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /www/wwwroot/tx.nstarzx.cn/data/redis
appendonly yes
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
maxmemory 192mb
maxmemory-policy noeviction
